In [1]:
import pandas as pd
import requests
import json
import csv
import os

from sqlalchemy import create_engine

# Output File (CSV)
output_data_file = "Resources/clubs.csv"

In [15]:
url = pd.read_html("https://en.wikipedia.org/wiki/FIFA_Club_World_Cup")
clubs_country = url[3]
# clubs_country = pd.DataFrame(clubs_country) # Alap: This is not needed since read_html gives you DataFrame object.
clubs_country = clubs_country[["Season", "Hosts", "Champions"]]
clubs_country = clubs_country.rename(columns={"Champions" : "club"})
clubs_country

    Season    Hosts                  club
0     2000   Brazil      Corinthians[n 2]
1     2001    Spain  Tournament cancelled
2     2005    Japan             São Paulo
3     2006    Japan         Internacional
4     2007    Japan                 Milan
5     2008    Japan     Manchester United
6     2009      UAE        Barcelona[n 5]
7     2010      UAE        Internazionale
8     2011    Japan             Barcelona
9     2012    Japan           Corinthians
10    2013  Morocco         Bayern Munich
11    2014  Morocco           Real Madrid
12    2015    Japan             Barcelona
13    2016    Japan      Real Madrid[n 9]
14    2017      UAE           Real Madrid
15    2018      UAE           Real Madrid
16    2019    Qatar       Liverpool[n 11]
17    2020    Qatar                   NaN
18    2021    China                   NaN

In [29]:
# Outputting DataFrame to csv
with open(output_data_file, 'w') as csv_file:
    clubs_country.to_csv(csv_file, index=False)

In [34]:
# Reading players_20.csv file
players = "Resources/players_20.csv"
players_df = pd.read_csv(players)

# Selecting only the columns that I want
players_df = players_df[["long_name", "club", "joined"]]
players_df

,long_name,club,joined
0,Lionel Andrés Messi Cuccittini,FC Barcelona,7/1/2004
1,Cristiano Ronaldo dos Santos Aveiro,Juventus,7/10/2018
2,Neymar da Silva Santos Junior,Paris Saint-Germain,8/3/2017
3,Jan Oblak,Atlético Madrid,7/16/2014
4,Eden Hazard,Real Madrid,7/1/2019
...,...,...,...
18273,邵帅,Beijing Renhe FC,7/13/2018
18274,Mingjie Xiao,Shanghai SIPG FC,2/1/2019
18275,张威,Hebei China Fortune FC,1/1/2019
18276,汪海健,Shanghai Greenland Shenhua FC,2/1/2019
18277,潘喜明,Hebei China Fortune FC,NaN

In [37]:
# Creating a Roster of 2018 winning team and when the players join the team

# Merging DataFrames clubs_country and players_df
pyr_ctry_m = pd.merge(clubs_country, players_df, on="club")

# Filtering for 2018
pyr_ctry_m = pyr_ctry_m.loc[pyr_ctry_m["Season"] == 2018,:]

# Renaming long_name header to Roster
pyr_ctry_m = pyr_ctry_m.rename(columns={"long_name" : "Roster", "joined" : "Joined"})
pyr_ctry_m

     Season Hosts         club                             Roster     Joined
148    2018   UAE  Real Madrid                        Eden Hazard   7/1/2019
149    2018   UAE  Real Madrid                        Luka Modrić   8/1/2012
150    2018   UAE  Real Madrid                Sergio Ramos García   8/1/2005
151    2018   UAE  Real Madrid                   Thibaut Courtois   8/9/2018
152    2018   UAE  Real Madrid                         Toni Kroos  7/17/2014
153    2018   UAE  Real Madrid  Carlos Henrique Venancio Casimiro  7/11/2013
154    2018   UAE  Real Madrid                      Karim Benzema   7/9/2009
155    2018   UAE  Real Madrid                       Keylor Navas   8/3/2014
156    2018   UAE  Real Madrid     Francisco Román Alarcón Suárez   7/3/2013
157    2018   UAE  Real Madrid                     Raphaël Varane   7/1/2011
158    2018   UAE  Real Madrid              Daniel Carvajal Ramos   7/5/2013
159    2018   UAE  Real Madrid                  Gareth Frank Bale   9/2/2013
160    2018   UAE  Real Madrid     Marcelo Vieira da Silva Júnior   1/1/2007
161    2018   UAE  Real Madrid        James David Rodríguez Rubio  7/22/2014
162    2018   UAE  Real Madrid                         Luka Jović   7/1/2019
163    2018   UAE  Real Madrid            Marco Asensio Willemsen   7/1/2015
164    2018   UAE  Real Madrid    José Ignacio Fernández Iglesias   8/1/2010
165    2018   UAE  Real Madrid               Éder Gabriel Militão   7/1/2019
166    2018   UAE  Real Madrid             Lucas Vázquez Iglesias   7/2/2015
167    2018   UAE  Real Madrid                      Ferland Mendy   7/1/2019
168    2018   UAE  Real Madrid          Álvaro Odriozola Arzalluz   7/5/2018
169    2018   UAE  Real Madrid   Vinícius José de Oliveira Júnior  7/12/2018
170    2018   UAE  Real Madrid                 Mariano Díaz Mejía  8/29/2018
171    2018   UAE  Real Madrid                  Federico Valverde  7/22/2016
172    2018   UAE  Real Madrid              Rodrygo Silva de Goes   7/1/2019
173    2018   UAE  Real Madrid                 Lucas Silva Borges  1/26/2015
174    2018   UAE  Real Madrid                        Brahim Díaz   1/6/2019
175    2018   UAE  Real Madrid                              久保 建英   7/1/2019
176    2018   UAE  Real Madrid           Javier Hernández Carrera   7/1/2015
177    2018   UAE  Real Madrid               Sergio López Galache   7/1/2018
178    2018   UAE  Real Madrid           Álvaro Fidalgo Fernández   7/1/2016
179    2018   UAE  Real Madrid                Adrián de la Fuente   7/1/2018
180    2018   UAE  Real Madrid                Diego Altube Suárez   7/1/2018